#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/ a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
