#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get install software-properties-common -y 
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update -y
apt-get install haproxy=1.8.\* -y
echo "ENABLED=1" >> /etc/default/haproxy
sed -i "$ a \listen holberton\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin" /etc/haproxy/haproxy.cfg
sed -i "$ a \\\tserver 1623-web-01 35.231.95.4:80 check\n\tserver 1623-web-02 54.175.222.196:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
