#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -1 nginx
