#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -1 nginx
