#!/usr/bin/env bash
# Bash script that
sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap "sudo rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
