#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
m=1
h=0
while ((h<13))
do
    echo "Hour: $h"
    m=1
    while ((m<60))
    do
        echo "$m"
        (( m++ ))
    done
    let h++    
done
